src/app/appointment/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session, jsonify
from ..models import db, Patient, Appointment
from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta
import pytz


appointment_bp = Blueprint('appointment', __name__)

@appointment_bp.route('/appointments', methods=['GET', 'POST'])
def appointments():
    all_appointments = db.session.query(Appointment, Patient).join(Patient, Appointment.patient_id == Patient.id).all()
    patients = Patient.query.all()
    events = []
    
    recurrence_end_limit = datetime.now() + timedelta(weeks=52) 
    argentina_tz = pytz.timezone('America/Argentina/Buenos_Aires')

    for appointment, patient in all_appointments:
        # Evento inicial
        event = {
            'id': appointment.id,
            'title': f'Turno con {patient.name} {patient.lastname}',
            'start': argentina_tz.localize(datetime.combine(appointment.date, appointment.time)).isoformat(),
            'recurrence_type': appointment.recurrence_type,
            'recurrence_days': appointment.recurrence_days,
            'end_recurrence': recurrence_end_limit.strftime('%Y-%m-%d')
        }
        events.append(event)

    return render_template('appointments.html', events=events, patients=patients)


@appointment_bp.route('/appointments/create', methods=['POST'])
def create():
    try:
        date = request.form.get('date')
        time = request.form.get('time')
        patient_id = request.form.get('patient_id')
        recurrence_type = request.form.get('recurrence_type')
        recurrence_days = ','.join(request.form.getlist('recurrence_days'))

        if not patient_id or not date or not time:
            return jsonify({"error": "Missing required fields"}), 400

        appointment_date = datetime.strptime(date, '%Y-%m-%d').date()
        appointment_time = datetime.strptime(time, '%H:%M').time()
        recurrence_end = appointment_date + timedelta(weeks=52)

        # Guardar la cita sin crear múltiples filas en la base de datos
        new_appointment = Appointment(
            patient_id=patient_id,
            date=appointment_date,
            time=appointment_time,
            recurrence_type=recurrence_type,
            recurrence_days=recurrence_days,
            recurrence_end=recurrence_end
        )
        db.session.add(new_appointment)
        db.session.commit()

        return redirect(url_for('appointment.appointments'))

    except Exception as e:
        return jsonify({"error": str(e)}), 500

src/app/medsession/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, current_app, session
from ..models import db, User, Patient,Session
from flask_mail import Message
from werkzeug.utils import secure_filename
import os


medsession_bp = Blueprint('medsession',__name__)
ALLOWED_EXTENSIONS = {'txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif'}

def allow(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

@medsession_bp.route('/manage_session', methods = ['GET','POST'])
def manage_session():
    if request.method == 'POST':
        if 'create' in request.form:
            session_note = request.form['session_note']
            session_date = request.form['session_date']
            session_type = request.form['session_type']
            assist = request.form['assit']
            pay = request.form['pay']
            patient_id = request.form['patient_id']
            user_id = request.form['user_id']
            appointment_id = request.form['appointment_id']

            db.session.add(session_note=session_note,session_date=session_date,session_type=session_type,assist=assist,pay=pay,patient_id=patient_id,user_id=user_id,appointment_id=appointment_id)
            db.session.commit
        return redirect(url_for('medsession.medical_record'))
            
@medsession_bp.route('/upload', methods =['GET','POST'])
def upload_file():
    if request.methid == 'POST':
        if 'file' not in request.files:
            flash('NO file part')
            return
        file = request.files['file']
        if file.filename == '':
            flash('No selected File')
            return
        if file and allow(file.filename):
            filename = secure_filename(file.filename)
            file.save(os.path.join(current_app.config['UPLOAD_FOLDER'], filename))
            flash('Save sucessfully')
            
@medsession_bp.route('/medrecord', methods =['GET','POST'])
def medrecord():
    user_id = session['id'] 
    sess_patient = db.session.query(Session.session_note, Session.assist, Session.pay, Patient.name, Patient.lastname  ).join(Patient).filter(User.id == user_id).all()
    return render_template('medical_record.html', sess_patient=sess_patient)

src/app/patient/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session,current_app
from ..models import db, Patient, SocialSecurity, Session, Appointment
from werkzeug.utils import secure_filename
from datetime import datetime

patient_bp = Blueprint('patient', __name__)


@patient_bp.route('/patients', methods=['GET', 'POST'])
def patients():

    patients = db.session.query(Patient).join(SocialSecurity, Patient.social_id == SocialSecurity.id).all()
    socials = SocialSecurity.query.all()
    return render_template('patients.html', patients=patients, socials=socials)

@patient_bp.route('/patients/create', methods=['GET','POST'])
def create():
    if request.method == 'POST':
            user_id = session['id'] 
            name = request.form['name']
            lastname = request.form['lastname']
            age = request.form['age']
            number = request.form['number']
            email = request.form['email']
            country = request.form['country']
            social_id = request.form['social_id']            

            new_patient = Patient(name=name, lastname=lastname, age=age, number=number, email=email, country=country, social_id=social_id, is_active='yes', user_id=user_id)
            db.session.add(new_patient)
            db.session.commit()
            flash('Paciente creado exitosamente!', 'success')
        
            return redirect(url_for('patient.patients'))
    
@patient_bp.route('/patients/edit/<int:id>', methods=['GET','POST'])
def edit():
    patient = Patient.query.get(id)
    patient.name = request.form['name']
    patient.lastname = request.form['lastname']
    patient.age = request.form['age']
    patient.number = request.form['number']
    patient.email = request.form['email']
    patient.country = request.form['country']
    patient.social_id = request.form['social_id']   
    patient.is_active = request.form['is_active']        
    db.session.commit()
    flash('Paciente actualizado exitosamente!', 'success')

    return redirect(url_for('patient.patients'))

    
@patient_bp.route('/patients/delete/<int:id>', methods=['GET','POST'])
def delete():
    patient = Patient.query.get(id)
    db.session.delete(patient)
    db.session.commit()
    return redirect(url_for('patient.patients'))

@patient_bp.route('/patients/search', methods=['GET'])
def search_patients():
    query = request.args.get('query') 
    
    if query:
        search = Patient.query.filter(
            (Patient.name.ilike(f'%{query}%')) |
            (Patient.lastname.ilike(f'%{query}%')) |
            (Patient.number.ilike(f'%{query}%')) |
            (Patient.email.ilike(f'%{query}%'))
        ).all()
    
    return render_template('patients.html', search=search)

@patient_bp.route('/patients/<int:id>/history', methods=['GET','POST'])
def patients_history(id):
    patient = Patient.query.get(id)
    sessions = Session.query.filter_by(patient_id=id).all()
    return render_template('patients_history.html', patient= patient, sessions= sessions)

ALLOWED_EXTENSIONS = {'txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif'}

def allow(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

@patient_bp.route('/upload', methods=['GET', 'POST'])
def upload_file():
    if 'file' not in request.files:
        flash('No file part')
        return None
    file = request.files['file']
    if file.filename == '':
        flash('No selected file')
        return None
    if file and allowed_file(file.filename):
        filename = secure_filename(file.filename)
        file.save(os.path.join(current_app.config['UPLOAD_FOLDER'], filename))
        return filename

@patient_bp.route('/patients/<int:id>/session', methods = ['GET','POST'])
def patients_session(id):
    patient = Patient.query.get_or_404(id)
    if request.method == 'POST':
        session_note = request.form['session_note']
        session_date_str = request.form['session_date']
        session_type = request.form['session_type']
        assist = request.form['assist']
        pay = request.form['pay']
        session_file = upload_file()
        session_date = datetime.strptime(session_date_str, '%Y-%m-%d %H:%M')
         

        new_session = Session(
            patient_id=id,
            session_note=session_note,
            session_date=session_date,
            session_type= session_type,
            assist=assist,
            pay=pay,
            session_file=session_file,
            user_id = session['id']
 
        )
        db.session.add(new_session)
        db.session.commit()
        
        flash('Sesión creada exitosamente')
        return redirect(url_for('patient.patients_history', id=id))


    appointments= Appointment.query.filter_by(patient_id=id).all()

    return render_template('patients_session.html',patient=patient, appointments=appointments)
            

src/app/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session
from .models import db, User

auth_blueprint = Blueprint('auth', __name__)


@auth_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        name = request.form['name']
        lastname = request.form['lastname']
        email = request.form['email']
        registration = request.form['registration']
        password = request.form['password']
        
        user = User(name=name, lastname=lastname, email=email, registration=registration)
        user.set_password(password)
        
        db.session.add(user)
        db.session.commit()

        flash('Registration successful!', 'success')
        return redirect(url_for('auth.login'))
    
    return render_template('register.html')

@auth_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']

        user = User.query.filter_by(username=username).first()

        if user and user.check_password(password):
            session['user_id'] = user.id
            session['role'] = user.role
            flash('Login successful!', 'success')
            return redirect(url_for('home'))  # Redirect to the main page of the application

        flash('Invalid credentials', 'danger')
    
    return render_template('login.html')

@auth_blueprint.route('/logout')
def logout():
    session.pop('user_id', None)
    session.pop('role', None)
    flash('You have been logged out.', 'info')
    return redirect(url_for('auth.login'))

src/app/socialsecurity/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session
from ..models import db, SocialSecurity

social_bp = Blueprint('socialsecurity', __name__)

@social_bp.route('/social_security', methods =['GET', 'POST'])
def manage_social():
    if request.method == 'POST':
        if 'create' in request.form:
            # Crear nueva obra social
            name = request.form['name']
            new_social = SocialSecurity(name=name)
            db.session.add(new_social)
            db.session.commit()
            return redirect(url_for('socialsecurity.get_all'))

        elif 'update' in request.form:
            # Actualizar obra social
            social_id = request.form['social_id']
            social = SocialSecurity.query.get(social_id)
            if social:
                social.name = request.form['name']
                db.session.commit()
            return redirect(url_for('socialsecurity.get_all'))

        elif 'delete' in request.form:
            # Eliminar obra social
            social_id = request.form['social_id']
            social = SocialSecurity.query.get(social_id)
            if social:
                db.session.delete(social)
                db.session.commit()
            return redirect(url_for('socialsecurity.get_all'))

    # Para solicitudes GET, mostrar la tabla de todas las obras sociales
    return redirect(url_for('socialsecurity.get_all'))


# Ruta para obtener todas las obras sociales y mostrarlas en la plantilla
@social_bp.route('/social_security/all', methods=['GET'])
def get_all():
    socials = SocialSecurity.query.all()  #
    return render_template('social_security.html', socials=socials)

src/app/templates/home.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inicio - Sistema Psicólogos</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

    <div class="container">
        <div class="row justify-content-center mt-5">
            <div class="col-md-6">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <h3 class="card-title text-center">Bienvenido al Sistema para Psicólogos</h3>
                        <p class="text-center">Por favor, elige una opción:</p>
                        <div class="d-grid gap-2">
                            <a href="{{ url_for('auth.login') }}" class="btn btn-primary btn-lg">Iniciar Sesión</a>
                            <a href="{{ url_for('auth.register') }}" class="btn btn-success btn-lg">Registrarse</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap JS (opcional si no necesitas interactividad con JS) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

src/app/templates/patients.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pacientes</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
{% extends 'section.html' %}

{% block title %} Pacientes{% endblock %}

{% block content %}
<div class="container mt-5">
    <!-- Header -->
    <div class="d-flex justify-content-between align-items-center mb-4">
        <div>
            <form class="d-flex" action="{{ url_for('patient.search_patients') }}" method="GET">
                <input class="form-control me-2" type="search" name="query" placeholder="Buscar paciente" aria-label="Buscar">
                <button class="btn btn-outline-success" type="submit">Buscar</button>
            </form>
            <div class="container mt-5">
                <!-- Mensaje si no se encuentran pacientes -->
                {% if not patients %}
                <div class="alert alert-warning" role="alert">
                    No se encontraron pacientes que coincidan con el término de búsqueda.
                </div>
                {% endif %}
            </div>            
        </div>
        <!-- Botón para abrir el modal de creación de paciente -->
        <a href="#" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#createPatientModal">Nuevo Paciente</a>
    </div>

    <!-- Tabla de Pacientes -->
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th scope="col">Nombre</th>
                <th scope="col">Apellido</th>
                <th scope="col">Numero</th>
                <th scope="col">Obra Social</th>
                <th scope="col">Acciones</th>
            </tr>
        </thead>
        <tbody>
                {% for patient in patients %}
                <tr>
                    <td>{{ patient.name }}</td>
                    <td>{{ patient.lastname }}</td>
                    <td>{{ patient.number }}</td>
                    <td>{{ patient.social.name if patient.social else 'Sin obra social' }}</td>
                    <td>
                        <!-- Botón de editar -->
                        <button class="btn btn-sm btn-warning" data-bs-toggle="modal" data-bs-target="#updatePatientModal{{ patient.id }}">Editar</button>
                        
                        <!-- Formulario para eliminar -->
                        <form action="{{ url_for('patient.delete', id=patient.id) }}" method="POST" style="display:inline;">
                            <button class="btn btn-sm btn-danger" type="submit" onclick="return confirm('¿Estás seguro de eliminar este paciente?')">Eliminar</button>
                        </form>
                        <a href="{{ url_for('patient.patients_history', id=patient.id) }}" class="btn btn-sm btn-info">Ver Historial</a>
                        <a href="{{ url_for('patient.patients_session', id=patient.id) }}" class="btn btn-sm btn-success">Crear Sesion</a>
                        <!-- Modal para actualizar paciente -->
                        <div class="modal fade" id="updatePatientModal{{ patient.id }}" tabindex="-1" aria-labelledby="updatePatientLabel{{ patient.id }}" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="updatePatientLabel{{ patient.id }}">Actualizar Paciente</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <form method="POST" action="{{ url_for('patient.edit', id=patient.id) }}">
                                        <div class="modal-body">
                                            <input type="hidden" name="id" value="{{ patient.id }}">
                                            <div class="mb-3">
                                                <label for="name" class="form-label">Nombre</label>
                                                <input type="text" class="form-control" name="name" value="{{ patient.name }}" required>
                                            </div>
                                            <div class="mb-3">
                                                <label for="lastname" class="form-label">Apellido</label>
                                                <input type="text" class="form-control" name="lastname" value="{{ patient.lastname }}" required>
                                            </div>
                                            <div class="mb-3">
                                                <label for="email" class="form-label">Email</label>
                                                <input type="email" class="form-control" name="email" value="{{ patient.email }}" required>
                                            </div>
                                            <div class="mb-3">
                                                <label for="number" class="form-label">Número de Teléfono</label>
                                                <input type="text" class="form-control" name="number" value="{{ patient.number }}" required>
                                            </div>
                                            <div class="mb-3">
                                                <label for="age" class="form-label">Edad</label>
                                                <input type="number" class="form-control" name="age" value="{{ patient.age }}" required>
                                            </div>
                                            <div class="mb-3">
                                                <label for="country" class="form-label">País</label>
                                                <input type="text" class="form-control" name="country" value="{{ patient.country }}" required>
                                            </div>
                                            <div class="mb-3">
                                                <label for="social_id" class="form-label">Obra Social</label>
                                                <select class="form-select" id="social_id" name="social_id" required>
                                                    {% for social in socials %}
                                                        <option value="{{ social.id }}" {% if patient.social_id == social.id %}selected{% endif %}>{{ social.name }}</option>
                                                    {% endfor %}
                                                </select>
                                            </div>
                                            <div class="mb-3">
                                                <label for="is_active" class="form-label">¿Activo?</label>
                                                <select class="form-select" id="is_active" name="is_active" required>
                                                    <option value="yes">Sí</option>
                                                    <option value="no">No</option>
                                                </select>
                                            </div>

                                        </div>
                                        <div class="modal-footer">
                                            <button type="submit" class="btn btn-primary">Guardar Cambios</button>
                                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    

<!-- Modal para crear nuevo paciente -->
<div class="modal fade" id="createPatientModal" tabindex="-1" aria-labelledby="createPatientLabel" aria-hidden="true">
    <div class="modal-dialog">up
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="createPatientLabel">Nuevo Paciente</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form method="POST" action="{{ url_for('patient.create') }}">
                <div class="modal-body">
                    <div class="mb-3">
                        <label for="name" class="form-label">Nombre</label>
                        <input type="text" class="form-control" id="name" name="name" required>
                    </div>
                    <div class="mb-3">
                        <label for="lastname" class="form-label">Apellido</label>
                        <input type="text" class="form-control" id="lastname" name="lastname" required>
                    </div>
                    <div class="mb-3">
                        <label for="email" class="form-label">Email</label>
                        <input type="email" class="form-control" id="email" name="email" required>
                    </div>
                    <div class="mb-3">
                        <label for="number" class="form-label">Número de Teléfono</label>
                        <input type="text" class="form-control" id="number" name="number" required>
                    </div>
                    <div class="mb-3">
                        <label for="age" class="form-label">Edad</label>
                        <input type="number" class="form-control" id="age" name="age" required>
                    </div>
                    <div class="mb-3">
                        <label for="country" class="form-label">País</label>
                        <input type="text" class="form-control" id="country" name="country" required>
                    </div>
                    <div class="mb-3">
                        <label for="social_id" class="form-label">Obra Social</label>
                        <select class="form-select" id="social_id" name="social_id" required>
                            <option value="">Seleccionar Obra Social</option>
                            {% for social in socials %}
                                <option value="{{ social.id }}">{{ social.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="mb-3">
                        <label for="is_active" class="form-label">¿Activo?</label>
                        <select class="form-select" id="is_active" name="is_active" required>
                            <option value="yes">Sí</option>
                            <option value="no">No</option>
                        </select>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Guardar Paciente</button>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Bootstrap JS y Popper.js necesarios para que los modales funcionen -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>
{% endblock %}   

src/app/templates/patients_session.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Historia Clinica </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.9.0/dist/summernote.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.9.0/dist/summernote.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">

</head>
<body>
{% extends 'section.html' %}

{% block title %}Crear sesión{% endblock %}
<h1>Crear sesión de {{ patient.name }} {{ patient.lastname }}</h1>

{% block content %}
<form method="POST" action="{{ url_for('patient.patients_session', id=patient.id) }}">
    <div class="mb-4">
        <label for="session_note" class="form-label">Nota de la Sesión</label>
        <textarea id="session_note" name="session_note" class="form-control" rows="10"></textarea>
    </div>
    <div class="modal-body">
        <div class="mb-3">
            <label for="session_date" class="form-label">Fecha</label>
            <input type="text" class="form-control" id="session_date" name="session_date">
        </div>
    <div class="mb-4">
        <label for="assist" class="form-label">¿Asistió?</label>
        <select name="assist" class="form-control">
            <option value="yes">Sí</option>
            <option value="no">No</option>
        </select>
    </div>
    <div class="mb-4">
        <label for="pay" class="form-label">Pago</label>
        <select name="pay" class="form-control">
            <option value="paid">Pagado</option>
            <option value="unpaid">No Pagado</option>
        </select>
    </div>
    <div class="mb-4">
        <label for="session_type" class="form-label">Tipo de terapia</label>
        <select name="session_type" class="form-control">
            <option value="therapy">Terapia</option>
            <option value="enterview">Entrevista</option>
            <option value="family">Terapia Familiar</option>
            <option value="gestalt">Terapia Gestalt</option>
        </select>
    </div>
    <div class="mb-3">
        <label for="appointment_id" class="form-label">Turno</label>
        <select class="form-select" id="appointment_id" name="appointment_id" required>
            {% for appointment in appointments %}
                <option value="{{ appointment.id }}" {% if appointment.appointment_id == appointment.id %}selected{% endif %}>{{ appointment.recurrence_type }}</option>
            {% endfor %}
        </select>
    </div>
    <div class="mb-4">
        <label for="file" class="form-label">Subir Archivo</label>
        <input type="file" name="file" class="form-control">
    </div>
    <button type="submit" class="btn btn-primary">Guardar Sesión</button>
</form>

<!-- Formulario para subir archivos -->
<h3 class="mt-5">Subir Archivos (PDF o Imágenes)</h3>
<form method="POST" enctype="multipart/form-data" action="{{ url_for('patient.upload_file') }}">
    <div class="mb-4">
        <label for="file" class="form-label">Seleccionar Archivo</label>
        <input type="file" id="file" name="file" class="form-control" accept=".pdf, image/*">
    </div>
    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <button type="submit" class="btn btn-secondary">Subir Archivo</button>
    </div>
</form>

<hr>

<!-- Lista de archivos adjuntos -->
<div class="mt-5">
    <h3>Archivos Adjuntos</h3>
    <ul class="list-group">
        {% for file in attached_files %}
        <li class="list-group-item">
            <a href="{{ url_for('static', filename='uploads/' + file) }}" target="_blank">{{ file }}</a>
        </li>
        {% else %}
        <li class="list-group-item">No hay archivos adjuntos disponibles.</li>
        {% endfor %}
    </ul>
</div>

<!-- Scripts -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
<script>
    $(document).ready(function() {
        $('#session_note').summernote({
            height: 300,
            placeholder: 'Escriba los detalles de la sesión aquí...'
        });
    });
</script>
<!-- Flatpickr JS -->
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        flatpickr("#session_date", {
            dateFormat: "Y-m-d H:i", 
            altInput: true,
            altFormat: "F j, Y H:i", 
            enableTime: true,
            allowInput: true
        });
    });
</script>

</body>
</html>
{% endblock %}